defmodule VeChain.Contracts.VTHO do
  @moduledoc """
  VTHO (VeThor) token contract interface.

  VTHO is VeChain's gas token, generated by staking VET.
  It follows the VIP-180 standard (compatible with ERC-20).

  The VTHO contract is deployed at the same address on all networks:
  `0x0000000000000000000000000000456E65726779`
  """
  @vtho_address "0x0000000000000000000000000000456E65726779"

  use VeChain.Contract,
    abi_file: "priv/abi/energy.json",
    default_address: @vtho_address
end
